### ISSUE TITLE
Order To Stock - Joomla based Inventory and RVNL Functionality

### ISSUE THREAD

**Issue by hariharan-isgec** [Isgec/IT-Services#10]
A LN Integrated module to maintain Inventory of Item at Isgec Warehouse, Site Warehouse and with, Supplier end for materials issued for subcontracting.
=======

![image](https://user-images.githubusercontent.com/43699418/51817947-00f58b00-22f3-11e9-9ce0-791ab4fc97b3.png)

[RVNL Invoicing.pdf](https://github.com/Isgec/IT-Services/files/2801645/RVNL.Invoicing.pdf)

**Comment by hariharan-isgec** [comment]
Scenerios to Consider
==============
-Finished / Semi Finished Material lying with Vendor for which He has raised Invoice
-In Divisional W/H, Sanctionwise utilisation
-In Divisional W/H, One Time Sanction (i.e. When Item is issued out of W/H, the Sanction should not get free for further order)
- In Divisional W/H, allocation of Cost to another Project befor Customer Invoicing stage, to block the Project Sanction 
- In Inventory Module (DC), Value Added Item should have suffix to descrbe the Value Addtion

**Comment by hariharan-isgec** [comment]
Scenario  Dry Run 
-------------
**Scenario   1** | Normal   Project, Virtual Warehouse, PO, One billing advice in same Project
Check Points
-----------
1. All Checkes in Requisition, PO, Receipt are working fine
2. Assignment of Quantity and Balance Quantity Calculation on DC
3. Modifications in Purchase Bill Approval Memo
4. Closure of Delivery Challan Vendor DC
5. Generation of DC from Physical WH and its closure
6. Check on Billing Advice-**Tested**
7. Proper Sanction consumption in case of same/different Project-**Tested**
8. Proper Inventory movement
9. Cost booking in Project
10. Sale Invoice Printing changes when issue from Physical WH

**Comment by 0340LalitGupta** [comment]
Code commited in WebSPMT1
Order To Stock - Joomla based Inventory and RVNL Functionality

**Comment by hariharan-isgec** [comment]
RVNL Functi0onality will be takenup based on subsequent Inputs by accounts based on Inventory Data created by this new functionality
