### ISSUE TITLE
Group Mediclaim Enrollment Workflow

### ISSUE THREAD

**Issue by hariharan-isgec** [Isgec/IT-Services#11]
![whatsapp image 2019-02-04 at 10 26 15](https://user-images.githubusercontent.com/43699418/52191391-6ce37080-286a-11e9-9091-60ad981c5a71.jpeg)
![whatsapp image 2019-02-04 at 10 19 45](https://user-images.githubusercontent.com/43699418/52191399-7076f780-286a-11e9-9164-a14f91650cde.jpeg)

GMC Portal Workflow
========
During the Policy Period
-------
OPEN for New Employee -> Submitted by Employee - > Validated/Edited by HR -> Enrolled for Insurance

1. **HR Employee** creates New Employee Entry in HRMS (A Scheduler will push this data into Odoo)
2. **Employee** will see blank form in GMC Portal. They will fill the data and submit for HR Validation or Send data in Excel Template to HR who will upload in to GMC Portal.
3. **HR Employee** will validate the data **Validated**. (LoginID , Date and time of Validation will be stored) OR **HR Employee** can alternatively download the bulk Data into Excel update the 'Validated' column and upload back
4. **Employee** will be able to see the status of his application.
5. **Accounts-Insurance Employee** can see all the data with the status
6. **Accounts-Insurance Employee**  can filter the data and download into Excel
7. **Accounts-Insurance Employee**  can update the status as **Enrolled for Insurance** (LoginID , Date and time will be stored) OR **Accounts-Insurance Employee** can alternatively download the bulk Data into Excel update the **Enrolled for Insurance** column and upload back
[GROUP MEDICLAIM MID-YEAR ENROLLMENT.xlsx](https://github.com/Isgec/IT-Services/files/2955270/GROUP.MEDICLAIM.MID-YEAR.ENROLLMENT.xlsx)

During the Annual Renewal Period
-------
OPEN for All Employee -> Submitted by Employee - > Validated/Edited by HR -> Enrolled for Insurance

1. **HR Employee** will OPEN new Policy Period. 
2. **Employee** can copy their Data from Previous Policy period and make modification OR create new entries
3. **Employee** will submit the Data for HR Validation, HR can add/edit on behalf of Employee.
4. **HR Employee** will see all submitted data and can open it and Update each record as **Validated**. (LoginID , Date and time of Validation will be stored) OR **HR Employee** can alternatively download the bulk Data into Excel update the 'Validated' column and upload back
5. **Employee** will be able to see the status of his application.
6. **Accounts-Insurance Employee** can see all the data with the status
7. **Accounts-Insurance Employee**  can filter the data and download into Excel
8. **Accounts-Insurance Employee**  can update the status as **Enrolled for Insurance** (LoginID , Date and time will be stored) OR **Accounts-Insurance Employee** can alternatively download the bulk Data into Excel update the **Enrolled for Insurance** column and upload back

**Comment by hariharan-isgec** [comment]
@0340LalitGupta review the above requirement

**Comment by hariharan-isgec** [comment]
@RajeevKumarmbd review the requirement

**Comment by RajeevKumarmbd** [comment]
Database Design of Group Mediclaim
[Database Design of GMEW.xlsx](https://github.com/Isgec/IT-Services/files/2956485/Database.Design.of.GMEW.xlsx)
 Enrollment Workflow

**Comment by hariharan-isgec** [comment]
**Calculation** All Results to be stored in Database
==================
Covering Days = Policy Expiry  - Date of Joining
Applicable Pro Rate Premium = Covering Days / 365 x Applicable Annual Premium(with or without parents)
Premium = Sum Insured x Applicable Pro Rate Premium 
Age  = Policy Starting Date - Date of Birth (Round of Decimal)

**Comment by hariharan-isgec** [comment]
@0340LalitGupta publish the code in GitHub and confirm

**Comment by hariharan-isgec** [comment]
![image](https://user-images.githubusercontent.com/43699418/57056066-9ec77000-6cbd-11e9-9c4d-818c648f38c6.png)
