### ISSUE TITLE
Travel Module

### ISSUE THREAD

**Issue by 0340LalitGupta** [Isgec/IT-Services#13]
1. Budget Sanction
2. Travel Request [Budgeted / Non Budgeted]
3. Trip ID Creation
4. BTA Transaction Download
5. Monthly AMEX bill
6. AMEX Bill Validation by FCM
[Travel Module Logic Discussed on 22-02-2019.pdf](https://github.com/Isgec/IT-Services/files/2893215/Travel.Module.Logic.Discussed.on.22-02-2019.pdf)

**Comment by hariharan-isgec** [comment]
@RajeevKumarmbd please review the notes and start developing
@0340LalitGupta guid Rajeev
