### ISSUE TITLE
ODOO Development Environment - Rajeev

### ISSUE THREAD

**Issue by hariharan-isgec** [Isgec/IT-Services#15]
@RajeevKumarmbd Install and Configure Ubuntu and Odoo environment in your computer

**Comment by RajeevKumarmbd** [comment]
**Installed odoo 12 on ubuntu Version 18.04**
sudo apt-get install postgresql -y
sudo apt --fix-broken install

sudo dpkg -i /home/rajeev/Downloads/odoo_12.0.20181003_all.deb
sudo apt-get install -f 
sudo dpkg -i /home/rajeev/Downloads/odoo_12.0.20181003_all.deb

sudo apt update
sudo apt install python3-pip

sudo -H pip3 install vobject qrcode
sudo -H apt install libldap2-dev libsasl2-dev
sudo -H pip3 install pyldap
sudo -H pip3 install num2words

--On Running Oddo first time http://localhost:8069
Database rajeev-dev
Password qwerty123

Admin Login
rajeev.kumar2@isgec.co.in, pwd qwerty123

**Comment by RajeevKumarmbd** [comment]
Gmc Module Develop in Odoo Framework
gmc_module.zip
