### ISSUE TITLE
Employee Cost Allocation Module

### ISSUE THREAD

**Issue by hariharan-isgec** [Isgec/IT-Services#17]
Following Modules to be developed for Cost Estimate
1. Actual Cost Allocation  - Pecentage Based  :Repository: **Isgec/EmpSalary**
2. Actual Cost Allocation  - Hrs Based : Repository: **Isgec/EmpSalaryEngHRS**
3. Actual Cost Allocation  - PO Weight Based : Repository: **Isgec/EmpSalaryPOWeight**

4. Voucher Posting
5. Cost Estimation  - Mandays based
6. Cost Estimation  - PO Weight based
7. Accounts Process Management and Dashboard :Repository:I**sgec/EmpSalary_Accounts**,  **Isgec/EmpCostAllocationDashboard**

**Comment by hariharan-isgec** [comment]
@RajeevKumarmbd Develop Cost Estimation - Mandays based as per attached Template
[2.1-Budget-Loading manpower cost to Prj,cons,comm,qlty,safety,site deployed only.xlsx](https://github.com/Isgec/IT-Services/files/3385476/2.1-Budget-Loading.manpower.cost.to.Prj.cons.comm.qlty.safety.site.deployed.only.xlsx)

**Comment by hariharan-isgec** [comment]
@veena-isgec Create following Role in Baan for giving URL for accessing Cost Allocation software.
1. Manpower Cost Allocation - Percentage Basis - Open URL-http://192.9.200.146/EmpCost/UserPage.aspx?KeyUserCardNo='Logged in Employee Code'
2. Manpower Cost Allocation - Manhrs Basis - Open URL-http://192.9.200.146/EmpEngHrs/Main.aspx?KeyUserCardNo='Logged in Employee Code'

**Comment by hariharan-isgec** [comment]
**Enhancement Points and Process Flow**
1. Accounts will Trigger Action - > A new record for Month and Year will be added, previous months Effort data will be copied into for new Month and Year
2. When Departments Upload data, a Flag will be set indicating that the data is validated, non-validated department will appear in Defect Dashboard
3. In Excel Project Name to be displayed on Code selection
4. Project list to limit to division 
5. Data Validation for Percentage completion if all rows have 100%, then "Uploaded Successfully" else  "Upload failed due to Percentage error"

**Implementation Guidelines**
1. Create a MonthYear master having SlNo, Month, Year, Processed, Active
2. Month/Year Drop down to come from Month/Year master where Active=True
3. Accounts will have a page where they can the Next unprocessed Month and Year. When they Click button Active, the system will update the MonthYear master, set Processed =True and Active = True, All prevous month Active = False
4. Copy EmpEffort data of Previous Month and Insert with Active Month and Year
5. Create Seperate Excel for Seperate divisions
6. Put Project code and Description in Template
7. Add Vlookup above Project Code

**Comment by hariharan-isgec** [comment]
@veena-isgec @RajeevKumarmbd 
**Actual Cost Allocation - PO Weight Based**
Implementation Points
1. A view to be created in BaaN with following structure
![image](https://user-images.githubusercontent.com/43699418/61764055-6edbc480-adf5-11e9-9c6c-0946e392d523.png)

2. A seperate Module EmpPOWeight to be created with following functionality
a) KeyUserMappingPOWeight
b) A Form to download & upload AllocationType as per attached ExcelTemplate 
c) A Form to download Projectwise POWeight for a month as per attached ExcelTemplate with a button to Confirm (similar to Hrs module)

**Comment by hariharan-isgec** [comment]
@RajeevKumarmbd , provide URL for POWeight Employee Allocation URL
2. Cross check the spelling used for POWeight allocation type, PO should be in CAPs

**Comment by hariharan-isgec** [comment]
@veena-isgec 
Set the Divisions as follows in the LN_CostAllocation2 view
  UPDATE [EmpSalary].[dbo].[POEffort] SET [Division] = 'GEBD-Material Department' WHERE [Division]='Boiler'
  UPDATE [EmpSalary].[dbo].[POEffort] SET [Division] = 'EPC-Materials Department' WHERE [Division]='EPC'
  UPDATE [EmpSalary].[dbo].[POEffort] SET [Division] = 'SMD-Material Department' WHERE [Division]='SMD'

**Comment by veena-isgec** [comment]
done

**Comment by RajeevKumarmbd** [comment]
Live URL of PO Weight Based
http://192.9.200.146/EmpSalaryPOWt/Home.aspx?KeyUserCardNo=GEBD-Material%20Department

**Comment by hariharan-isgec** [comment]
> @veena-isgec Create following Role in Baan for giving URL for accessing Cost Allocation software.
> 
> 1. Manpower Cost Allocation - Percentage Basis - Open URL-http://192.9.200.146/EmpCost/UserPage.aspx?KeyUserCardNo='Logged in Employee Code'
> 2. Manpower Cost Allocation - Manhrs Basis - Open URL-http://192.9.200.146/EmpEngHrs/Main.aspx?KeyUserCardNo='Logged in Employee Code'
> 3. Manpower Cost Allocation - Accounts Screen-Open URL http://192.9.200.146/EmpSalary_Accounts/EmpAccountMain.aspx
>    @veena-isgec add another role for giving URL as follws
> 4. Manpower Cost Allocation - POWeight Basis - Open URL http://192.9.200.146/EmpSalaryPOWt/Home.aspx?KeyUserCardNo='Logged in Employee Code'

@veena-isgec Rollout Point No 4

**Comment by hariharan-isgec** [comment]
Post User Training User Requirements
=========================
1. In case of Departments who will give Input as Percentage, a Employee Login is required so that individual can input their Monthly Project Percentage data.
2. The Key User will get a compiled Excel for all the Employees mapped to him

Implementation Notes
===============
1. Develop Module in Odoo CostAllocation_module
2. Use existing hr_module to maintain Employee Master table for mapping to Loggedin User.
3. Employee Table of hr_module to have addtional fields for Department, Division
4. Project Master table will have ProjectID, Description, Division
5. ActiveMonth table will have DisplayName (as name), Month, Year, Active
6. Provision to make a particular month/year record as Active
7. EmployeeProjectPercentage table to record Employeewise Project wise Percentage Data for active Month/Year
8. KeyUser Mapping table with structure similar to already used Structure in CostAllocation Actual  module
9. Excel Output such that it cane be used to Import data into recently developed Costallocation module

@RajeevKumarmbd  to review and do

**Comment by hariharan-isgec** [comment]
Phase I rolled out
