### ISSUE TITLE
Major Incident - Hanging of Quick PTR Session

### ISSUE THREAD

**Issue by hariharan-isgec** [Isgec/IT-Services#3]
@veena-isgec Create MBF for this issue and record observations and action taken so far in GitHub

**Comment by dhirendra-isgec** [comment]
From: Sriharsha Bonthu [mailto:s.bonthu@pathinfotech.com] 
Sent: 05 December 2018 15:57
To: DCADMIN
Cc: dhirendra.singh@isgec.co.in; Vikram Bansal; sqldba; Vmanageit
Subject: Re: Please Log a complaint for ERPDB - 192.9.200.129 Server / ISGEC / Call Id - 87
 
Hello Team,
 
In regards to the slow performance issue registered we have done the health check for the database. Below  are the steps performed during the remote session:
-checked for the long running queries  and we have found there were no long running queries.
- checked for the CPU extensive queries.
- indexes have been rebuild recently.
- there were no blocked sessions.
- we found log size for the database "inforerpdb" had grown to 35879.93 MB and we have shrink the log size after taking the backup of the files.
- Log shipping was in sync.
- checked errors with the event viewer, no errors related to the database.
 
 
Thanks & Regards, 
Sreeharsha Bonthu 
Consultant DBA| Path Infotech Limited |(M) 91-9908430803 
E-1, Sec 63, Noida – 201301, India | (T) +91-120-4726 100 / (D) 226 
consulting | learning | outsourcing | technology 
 
________________________________________
From: Vmanageit
Sent: Wednesday, December 5, 2018 12:37 PM
To: Sriharsha Bonthu
Cc: dhirendra.singh@isgec.co.in; DCADMIN; Vikram Bansal; sqldba
Subject: RE: Please Log a complaint for ERPDB - 192.9.200.129 Server / ISGEC / Call Id - 87 
 
Hi Sriharsha,
 
Please have a look into this issue.
 
Regards
Ajay Singh Thakur
vManageIT HelpDesk  | Path Infotech Limited | E-mail : vmanageit@pathinfotech.com
E-1, Sec 63, Noida – 201301, India | (T) +91-120-4726 199, 198 | (F) +91-120-4726 200
consulting  |  outsourcing  |  learning  |  technology              
________________________________________
Pl. share your valuable feedback at dba.feedback@pathinfotech.com

**Comment by hariharan-isgec** [comment]
Action taken
